on:
  push:
    branches: [ main ]

jobs:      
  check-for-tag:
    runs-on: ubuntu-latest
    outputs:
      tagged: ${{ steps.check.outputs.flag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: check
        env:
          FLAG: true
        run: |
          TAGS=$(git tag --points-at ${{ github.sha }})
          if [ -z "$TAGS" ]; then
            FLAG=false
          fi
          echo "flag=$FLAG" >> "$GITHUB_OUTPUT"

  build:
    needs: [ check-for-tag ]
    runs-on: ubuntu-latest
    if: needs.check-for-tag.outputs.has-tag
    steps:
      - run: echo "done"
