on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check-for-tag:
    runs-on: ubuntu-latest
    outputs:
      has-tag: ${{ steps.check.outputs.flag }}
    steps:
      - uses: actions/checkout@v4
      - id: check
        run: |
          TAGS=$(git tag --points-at ${{ github.sha }})
          echo $TAGS
          if [ -z "$TAGS" ]; then
            echo "no tags present"
          fi
