on:
  push:
    branches: [ main ]

jobs:      
  check-for-tag:
    runs-on: ubuntu-latest
    outputs:
      tagged: ${{ steps.check.outputs.flag || true }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: check
        run: |
          TAGS=$(git tag --points-at ${{ github.sha }})
          echo $TAGS
          if [ -z "$TAGS" ]; then
            echo "no tags for commit"
            echo "flag=false" >> "$GITHUB_OUTPUT"
          fi
          

  build:
    needs: [ check-for-tag ]
    runs-on: ubuntu-latest
    if: needs.check-for-tag.outputs.tagged == 'true'
    steps:
      - run: echo "done"
