on:
  workflow_dispatch:

jobs:
  trigger-run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/callable.yml/dispatches \
          -d '{"ref":"main"}'
